version: '3'

services:
  php:
    image: php:8.2-apache
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shiftme
    command: ["bash", "-c", "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apache2-foreground"]

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--bind-address=0.0.0.0"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
